export class User{
    socialUserId:number;
    firstname:string;
    lastname:string;
    email:string;
    avatarphotoid:number;
    birthday:Date;
    password:string;
    gender:string;
    phoneNumber:string;
    aboutme:string;
    city:string;
    groupid:number;
    comments:any[];
    userPosts:any[];
    userPhotos:any[];
    likesComments:any[];
    messageAuthor:any[];
    messageReceiver:any[];
}